### ISSUE TITLE
Testing migrations

### ISSUE THREAD

**Issue by anselmdk** [patricknelson/silverstripe-migrations#3]
I'm writing a migration which splits a table into different tables, and in order to do that I'm collecting all data in an array.
Before I want to run the migration - and while developing, I'd like to check if I'm properly populating the array. So far I'm doing that by running `up` and emptying the `DatabaseMigrations` table for the next try, it would be nice if there would be a test method for dumping data like this while writing bigger migrations.

**Comment by patricknelson** [comment]
I've written some code of my own to have access to the SilverStripe framework OUTSIDE of a typical page/controller, here: https://gist.github.com/patricknelson/891ce9a8f5fc79894f9b

Basically just do this in your file `workbench/test.php`:

``` php
<?php
// Initialize framework.
require_once(__DIR__ . "/../ebayinc/framework.php");

$migration = new MigrationName();
$migration->up();

```

Try that out. Anything beyond that, in this module, would be easily outside of scope. I think I'd rather setup a separate project/module to make this more easily accessible (e.g. a workbench module).

**Comment by patricknelson** [comment]
That or maybe implement the `--pretend` option I've been looking to do (see the README.md in the root).

**Comment by anselmdk** [comment]
Thanks for those suggestions @patricknelson - I really like the idea of a workbench module, I don't know why I've never thought of that. I often tend to build a "test task" on my projects for exactly that.

**Comment by patricknelson** [comment]
No problem. Unfortunately, SIlverStripe doesn't natively support breaking out of their `main.php` entry point. IMPORTANT: Just make sure that your test/workbench area isn't made available in production. Either don't upload it or setup an `.htaccess` file like:

```
# Allow access from private network and loopback only.
Order deny,allow
Deny from all
Allow from 127.0.0.0/8
```

SO that only your local network machine is able to submit requests to that dir. Good luck and happy coding.

**Comment by anselmdk** [comment]
Yeah, I was actually thinking of building one that could be underneath the document root. I usually place my SilverStripe installation inside of a `public` which I bootstrap using my https://github.com/titledk/ttools-silverstripe. Maybe I'll make such a workbench part of that module. If you want to contribute with that code bit of yours, I'd welcome a pull request.

**Comment by anselmdk** [comment]
@patricknelson I just added it to the module.

**Comment by patricknelson** [comment]
Problem with this so far is:
1. Using this as-is, is I think, a security vulnerability since it bypasses the processing that is necessary in the `framework/main.php` file (which filters input to prevent a remote attacker from putting the production site into development mode, for example).
2. This bypassing is necessary due to the fact that SS absolutely must route _everything_ to a controller (which we need to avoid for our rapid prototyping) so this needs to be located in a subdirectory which has been explicitly denied access to outsiders via `.htaccess` rules outlined above. https://github.com/patricknelson/silverstripe-migrations/issues/3#issuecomment-103343569

As I see it (opinion here), this is a bit of an issue with the SilverStripe model in general (MVC implementation) since you do not have an option, currently as it is rolled out, to incorporate critical framework bootstrapping while still not being always directed to a controller 100% of the time (i.e. maybe just defining your own routes separately, a la Laravel or countless other frameworks or standalone routers).

So unfortunately, this forces us (since we're writing code that cannot modify core) to avoid a certain file entirely (i.e. `framework/main.php`) which unfortunately also carries with it the overhead of the other things it does (mixing of concerns instead of strict separation of concerns) like the filtering of user input, e.g. https://github.com/silverstripe/silverstripe-framework/blob/3.1/main.php#L114
